User creation
albjoaov/mercadolibre-wannabe pull request #1
Opened 2020-03-27 08:15 UTC by albjoaov

Oi, Alberto! A jornada do Dev Eficiente tá sendo um aprendizado arretado! Seja na live ou no grupo!

Contudo, tive que priorizar uma grande entrega no trabalho nessa última semana e, infelizmente, não pude criar o PR a tempo. Mas antes tarde do que nunca, consegui iniciar o projeto.

Algumas observações:

1. Acabei incluindo alguns arquivos a mais de configuração geral que fugiam um pouco do escopo da atividade de registrar um usuário. Portanto você verá alguns commits com a tag `master` e o tipo `infra`. Contudo, apesar de fugir do escopo, gostaria que pudesse avaliar também, visto que estou com um problema, inclusive, em uma dessas classes de configuração:

É no Spring Security. Ao adicioná-lo como dependência, por padrão, ele adiciona uma camada de autenticação e autorização nas rotas. Porém, mesmo criando a classe de configuração não consegui retirar esse problema. 

Os endpoints retornam sempre 403, seja no client do Swagger ou no Postman. Até achei que seria essa propriedade que foi adicionada no `application.properties`: `server.servlet.context-path=/api`, já que ela me causou problema na configuração do Swagger de rotas lidas e teoricamente no Security também.

Bom, não consegui fazer a request com o Security, consequentemente não consegui realizar o hash corretamente da senha.

2. Existem alguns comentários de TODO, já que são lugares ainda que estou em dúvida, mas todos são de configurações gerais do projeto.

3. Os commits estão bem separados. Cada classe/modificação adicionada está num commit correto. Por exemplo: Adicionei uma classe Main para testes rápidos, daí ela pertence a esse commit: `[master] feat: add playground class 817a969`

2020-03-27 10:30 UTC, asouza requested changes

2020-03-27 10:30 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/SuperEntity.java
> +public abstract class SuperEntity {
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho. Uma leitura simples e que introduz bem o assunto https://www.sonarsource.com/resources/white-papers/cognitive-complexity.html*
+
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*

A classe abstrata vem para fazer com que a pessoa não escreva os atributos na classe filha. Por outro lado ela não tem nenhum método abstrato e provavelmente não será utilizada em nenhum ponto do código com polimorfismo. É importante que toda classe nova aumenta a dificuldade de entendimento do sistema, ainda mais uma classe que define atributos que não são necessários para todas as outras. Nem toda classe tem createdAt, updateAt e muito menos version para tratamento de lock otimista. 

Recomendo fortemente apagar a SuperEntity. O que ela faz por você pode ser substituído pela criação de um atalho na ide onde a pessoa pode gerar tudo isso com um ctrl+espaço. Se uma classe abstrata não tem método abstrato, ela não deveria existir.

2020-03-27 10:30 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/User.java
> +	public void setEmail (String email) {
*Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

Não temos atualização parcial do User, portanto não precisamos de um setter :)

2020-03-27 10:30 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/User.java
> +	public String getEmail () {
*Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

Também não recuperamos o email ainda, aqui também pode ser apagado

2020-03-27 10:30 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/User.java
> +	public User (String email, String password) {
*Deixamos pistas que facilitem o uso do código onde não conseguimos resolver com compilação.*

Como que o ponto de código que invoca esse construtor sabe que não deve aplicar o algoritmo de hash no password? Caso ele aplique, aqui vamos fazer o hash do hash. Que dica você poderia deixar para ajudar a prevenir esse problema?

2020-03-27 10:30 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/config/AuditorAwareImpl.java
> +public class AuditorAwareImpl implements AuditorAware<User> {
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho. Uma leitura simples e que introduz bem o assunto https://www.sonarsource.com/resources/white-papers/cognitive-complexity.html*

Sugiro remover aqui também. Se não estamos usando, não devemos ter. Cada classe nova aumenta a carga cognitiva do sistema, então cada uma delas precisa merecer ser criada.

2020-03-28 02:09 UTC, albjoaov commented on src/main/java/com/mercadolibrewannabe/model/User.java
> +	public void setEmail (String email) {
Concordo! Isso também serve pra os métodos de acesso para `password`?

2020-03-28 02:09 UTC, albjoaov commented on src/main/java/com/mercadolibrewannabe/model/User.java
> +	public String getEmail () {
Concordo! Isso também serve pra os métodos de acesso para `password`?

2020-03-28 02:16 UTC, albjoaov commented on src/main/java/com/mercadolibrewannabe/config/AuditorAwareImpl.java
> +public class AuditorAwareImpl implements AuditorAware<User> {
Concordo! Minha intenção era criar a infraestrutura para utilizar o `@CreatedDate` e `@LastModifiedDate`, acabei fazendo um passo a mais, sem necessidade, que seria para gravar também o usuário utilizado na operação

2020-03-28 02:36 UTC, albjoaov commented on src/main/java/com/mercadolibrewannabe/model/SuperEntity.java
> +public abstract class SuperEntity {
Concordo completamente com o primeiro parágrafo e a frase da complexidade do código. Porém, queria debater alguns pontos:

1. O problema seria a herança em si? Seria melhor uma composição? Um `@Embeddable`   (não testei se funciona ainda) teria uma funcionalidade mais positiva?

2. O problema seria a herança de uma classe abstrata? Ou porquê ela não tem métodos? Qual seria o possível problema que estaria criando? Utilizei mais por uma questão semântica, mas a minha intenção era simplesmente evitar a repetição de um código "boilerplate" (explico melhor no ponto 3). Com isso evito a manipulação com os atributos de data de criação, atualização e versionamento e todas as suas anotações.

3. Tenho a intenção de continuar o projeto após a jornada, e tive uma boa experiência no trabalho com esse tipo de herança. Por isso também que até me adiantei com o  `@Version`, mas posso retirá-lo sem problema, visto que não será usado agora, bem como o `@LastModifiedDate`.

Dito isso, gostaria de saber alternativas visto que, acho legal essa preocupação, mas também acho interessante manter essa responsabilidade atrelada a outra entidade de maneira isolada, entende? Acha besteira ou desnecessário? 
Entendo que escrever esse "boilerplate" é uma é um gasto de tempo irrelevante, já que posso ate salvar um comando na IDE, como você falou. Mas é mais pela garantia de que se estivesse num projeto com várias pessoas ninguém esqueceria. Além de que enxergo uma associação clara de todos entre a classe que carrega essa responsabilidade, como no caso da `SuperEntity` e uma abstração que carrega atributos padrão de modelos do sistema.

2020-03-28 03:23 UTC, albjoaov commented on src/main/java/com/mercadolibrewannabe/model/User.java
> +	public User (String email, String password) {
Criei um "meio de campo" para o hashing. Assim fica mais explícito, certo?

2020-03-28 03:39 UTC, albjoaov commented on src/main/java/com/mercadolibrewannabe/model/User.java
> +	public User (String email, String password) {
@asouza Alberto, gostaria também de uma ajuda em relação ao Spring security. 

Precisei adicioná-lo como dependencia para incluir o BCryptEnconder. Porém, por padrão, ele deixa todas as rotas desautorizadas, ou seja, retornando 401.

Para contornar isso, vários tutoriais indicam criar essa classe de configuração que criei, a `SecurityConfig`. Porém, quando faço isso, ele não só continua sem receber a request como passa a retornar 403. Não sei mais o que fazer. Podes me ajudar? Tenho certeza que é besteira pois já fiz isso faz tempo, mas agora não lembro mais, infelizmente.

2020-03-28 04:15 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/SuperEntity.java
> +public abstract class SuperEntity {
A minha recomendação para tirar vem do fato que a SuperEntity faz com que todas as classes do sistema fiquem amarradas com uma classe mãe frágil, já que é uma classe criada dentro do próprio sistema. Qualquer alteração que você fizer nela, impacta em todas as classes do sistema. 

Você poderia até trocar por composição, mas realmente o fato aqui é que você não tem comportamento para aproveitar. 

Sobre a obrigatoriedade de usar a classe mãe também é uma sensação.. Como o sistema não tem nenhum lugar que recebe uma superentity como argumento, ninguém necessariamente precisa implementar. 

Mas assim, não considero que seja uma coisa restritiva. Não considero uma boa tática pq não vejo nenhum ganho... O fato de escrever os atributos, como disse, poderia até ser um atalho da sua ide.

2020-03-28 04:15 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/User.java
> +	public void setEmail (String email) {
sim :)

2020-03-28 04:15 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/User.java
> +	public String getEmail () {
sim :)

2020-03-28 04:16 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/User.java
> +	public User (String email, String password) {
Lá na classe que tem o main, você desabilita o carregamento do Security por enquanto. @SpringBootApplication(exclude = { SecurityAutoConfiguration.class })

2020-03-28 04:16 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/config/AuditorAwareImpl.java
> +public class AuditorAwareImpl implements AuditorAware<User> {
Saquie, acho que pode ficar para depois mesmo :).

2020-03-28 04:18 UTC, asouza approved these changes
Go!

2020-03-30 06:37 UTC, merged