Category creation
albjoaov/mercadolibre-wannabe pull request #3
Opened 2020-04-05 08:49 UTC by albjoaov

Alberto, tenho alguns questionamentos

- Posso melhorar de alguma forma a generalização do validator abstrato para campos únicos? 

- Na linha trinta do `UniqueValidator` eu tenho : `Optional<E> entityByField = findEntityByField((F) target)`. O lint do IntelliJ reclama que não chequei a possibilidade do cast dessa forma:
>  Unchecked cast: 'java.lang.Object' to 'F' 
Besteira, certo? Visto que isso só daria problema se quem estiver desenvolvendo, incluir os generics errados.

- Tive que implementar o método `protected abstract Class<F> getFormClass();` nas classes que extendem o UniqueValidator para pegar a Classe do Form. É possível buscá-la sem isso com o Generics?

- Não tenho muita experiência em "auto-relacionamentos" com a JPA. Existe uma saída melhor do que a apresentada?

2020-04-05 10:51 UTC, asouza requested changes

2020-04-05 10:51 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/Category.java
> +public class Category extends SuperEntity {
Apenas uma sugestão aqui. Realmente a super entity divide a atenção da classe e não entrega nada em troca. Ela tem n atributos que poderiam ser declarados através de um atalho do ide não é o tipo de compensação que você busca quando parte para uma herança.

2020-04-05 10:51 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/Category.java
> +	@OneToOne(fetch = FetchType.LAZY)
Você pode ter várias filhas para uma mãe. @ManyToOne fica melhor. Sobre o auto relacionamento, eu considero assim ótimo :).

2020-04-05 10:51 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/form/CategoryForm.java
> +			UUID uuid = UUID.fromString(parentCategoryId);
A utilização do UUID é para experimentar? Ou tem algum motivo mais lógico que eu não estou enxergando?

2020-04-05 10:51 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/validation/UniqueValidator.java
> +public abstract class UniqueValidator<F extends AbstractForm, E extends SuperEntity> implements Validator {
*Avaliamos de forma lógica o nível de complicação de cada trecho de código. Aqui não tem espaço para feeling. Usamos a teoria da carga cognitiva e medimos o nível de pontos de entendimentos necessário por trecho. Uma leitura simples e que introduz bem o assunto https://www.sonarsource.com/resources/white-papers/cognitive-complexity.html*

A carga intrinseca aqui é muito alta. Você tem uma classe mãe com uma tipagem genérica que utiliza a palavra extends e duas classes abstratas. Também tem diversos métodos abstratos que as filhas precisam implementar. Eu lembro que também sugeri algo nessa linha na playlist da casa do código, mas a verdade que é para este caso, uma validação genérica construída em cima da bean validation vai ser bem mais simples. Ainda vai ter a carga intrinseca da pessoa saber da bean validation, mas pelo menos o trabalho para usar vai ser menor. Eu sugiro olhar a de tarcisio https://github.com/tacsio/bolao-api/blob/master/src/main/java/br/com/deveficiente/bolaoapi/shared/validator/UniqueValidator.java

2020-04-05 10:51 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/form/AbstractForm.java
> +public abstract class AbstractForm {
Aqui é o que chamamos de interface de marcação, no caso seria classe abstrata de marcação. Ela é muito complicada de entender, justamente pq existe para servir um propósito diferente de uma classe abstrata, que é de ter método abstrato que pode ser sobreescrito e usado através de polimorfismo.

2020-04-05 10:53 UTC, asouza commented
> Alberto, tenho alguns questionamentos
> 
> * Posso melhorar de alguma forma a generalização do validator abstrato para campos únicos?
> * Na linha trinta do `UniqueValidator` eu tenho : `Optional<E> entityByField = findEntityByField((F) target)`. O lint do IntelliJ reclama que não chequei a possibilidade do cast dessa forma:
> 
> > Unchecked cast: 'java.lang.Object' to 'F'
> 
> Besteira, certo? Visto que isso só daria problema se quem estiver desenvolvendo, incluir os generics errados.
> 
> * Tive que implementar o método `protected abstract Class<F> getFormClass();` nas classes que extendem o UniqueValidator para pegar a Classe do Form. É possível buscá-la sem isso com o Generics?
> * Não tenho muita experiência em "auto-relacionamentos" com a JPA. Existe uma saída melhor do que a apresentada?

2020-04-05 10:53 UTC, asouza commented
Foi mal, fechei sem querer.

2020-04-05 18:10 UTC, albjoaov commented on src/main/java/com/mercadolibrewannabe/model/Category.java
> +	@OneToOne(fetch = FetchType.LAZY)
Eita, é mesmo! Que viagem. Trocando aqui

2020-04-05 18:11 UTC, albjoaov commented on src/main/java/com/mercadolibrewannabe/model/form/CategoryForm.java
> +			UUID uuid = UUID.fromString(parentCategoryId);
Sim! Queria utilizar sem ser um long auto gerado padrão. Fora que uns projetos novos na empresa necessitam, gostaria de pegar mais cancha usando UUID. Pode ser?

2020-04-05 18:22 UTC, albjoaov commented on src/main/java/com/mercadolibrewannabe/model/Category.java
> +public class Category extends SuperEntity {
Alberto, sem querer ser chato e, talvez, insistir no mesmo erro, essa é uma abstração que vi que funciona bem na prática lá na empresa. Até então, gosto de adotá-la. 

Você pode detalhar mais esse lado **negativo** dela? Não consegui enxergar muito bem. 

Estando em um projeto em grupo, na minha cabeça, sempre existirá uma carga intrínseca de alguns padrões da empresa. 

Esse padrão da "SuperEntity" ou entidade base, como queira chamar, tange sobre atributos obrigatórios que toda entidade do sistema deve ter (por isso que me adiantei e coloquei o version também, gostaria de trabalhar com ele, ec). Por isso, realmente, quero que ela divida a atenção quando alguem ler essa classe.

Não entendi muito bem:
> não é o tipo de compensação que você busca quando parte para uma herança.

2020-04-05 19:00 UTC, albjoaov commented on src/main/java/com/mercadolibrewannabe/model/validation/UniqueValidator.java
> +public abstract class UniqueValidator<F extends AbstractForm, E extends SuperEntity> implements Validator {
Rapidamente, uma pergunta extra: Qual a diferença de usar o `implements Validator` para o `implements ConstraintValidator<ANNOTATION, FIELDTYPE>`? O último continua sendo capturado pelo @Valid do Spring, certo? Se sim, o Spring injeta esse `entityManager` para a classe?

Na minha opinião, existe uma carga intrínseca maior aí. Nesse caso eu preciso entender que preciso de uma Annotation na classe que chega no Controlador e a Classe que a implementa essa validação da anotação. 
Fora que não consigo reaproveitar a validação de unicidade de uma classe para outra usando o Spring Data JPA. Preciso da abstração do EntityManager e realizar a consulta usando CriteriaBuilder, CriteriaQuery, Root e Predicate. Na minha humilde opinião acho que está mais chatinho, já que temos mais abstrações kkkk.

Contudo, concordo que está com uma Carga cognitiva elevada dados generics incluídos na classe. Isso foi feito visto que tentei me inspirar nos vídeos de validação e template method da playlist da casa do código. Lá está parecido, o problema é que foi feito 2 validadores para a mesma classe (Livro) e para o mesmo form (LivroForm).

Poderia fazer da mesma forma, o problema que teria um validador de unicidade para cada Classe. Aí perde totalmente o sentido de tentar generalizar. Não gostaria de ter que fazer isso, existe alguma saída melhor? Acho que está quase igual ao código da API da CDC.

Posso tirar os generics e acho que vai continuar funcionando. Estou usando apenas para definir o tipo de retorno do `findEntityByField`. Posso mudar para um Object

```
protected abstract Optional<Object> findEntityByField(F form);
```

Mas teria que implementar o `public boolean supports (Class<?> clazz)` em cada Validador concreto, já que não tenho mais a referência do tipo do Form.

De imediato vejo isso, o que acha?

2020-04-05 19:01 UTC, albjoaov commented on src/main/java/com/mercadolibrewannabe/model/form/AbstractForm.java
> +public abstract class AbstractForm {
Justo! Concordo. Ela foi incluída por causa do Validador. Comentei lá sobre a situação, acho que o que decidirmos juntos lá irá refletir aqui

2020-04-06 09:33 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/Category.java
> +public class Category extends SuperEntity {
> Estando em um projeto em grupo, na minha cabeça, sempre existirá uma carga intrínseca de alguns padrões da empresa.

Na verdade os padrões servem para tentar diminuir a carga intrínseca. Pense nos padrões, quando realmente bem adotados,  como algo que te faz pensar menos :). Vou criar uma entidade, então já vou herdar de SuperEntity. A pessoa não necessariamente sabe o porque, mas vive bem e faz o que precisa ser feito.

> Esse padrão da "SuperEntity" ou entidade base, como queira chamar, tange sobre atributos obrigatórios que toda entidade do sistema deve ter (por isso que me adiantei e coloquei o version também, gostaria de trabalhar mais com ele, ec). Por isso, realmente, quero que ela divida a atenção quando alguem ler essa classe.

Sobre querer experimentar, estou completamente onboard. O version resolve um problema específico para objetos que podem ser salvos/alterados de maneira concorrente, o que realmente não é o caso para vários dos objetos. Experimente! 

Sobre a SuperEntity gerar qualquer obrigação sobre atributos obrigatórios, eu entendo a vontade. Por outro lado o sistema, em geral, não tem nada no código que gere essa restrição. Eu posso criar uma classe anotada com @Entity que não herda de BaseEntity e o sistema vai funcionar bem. Não existe nenhum lugar que receba SuperEntity como argumento. E o fato de não existir por si só, indica que ela é uma classe que não pertence aquele meio. *Idealmente, todo código escrito deveria ser chamado por alguém. Se não tem ninguém chamando, ele não deveria existir.*

> Foi mal, não entendi muito bem pq não seria, podes detalhar mais? hehe

A compensação para uma estrutura de herança, seja com classe concreta, abstrata ou interface é a  possibilidade de usar polimorfismo para realmente permitir uma evolução de parte do sistema sem ter que alterar em muitos lugares. Em geral você deveria ter algo parecido com isso:

```
metodo(SuperEntity entity){
}
```

Se não tem, é porque provavelmente ela meio que está sobrando. Você ainda continua precisando de alguém do review, regra do sonar ou qualquer coisa que seja para garantir essa obrigação. 

Mas assim, não é nada blocante. Essa é a minha visão e se você decidir continuar com ela está tudo bem :). Vamo que vamo!

2020-04-06 09:33 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/form/CategoryForm.java
> +			UUID uuid = UUID.fromString(parentCategoryId);
Jogue duro!

2020-04-06 09:38 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/validation/UniqueValidator.java
> +public abstract class UniqueValidator<F extends AbstractForm, E extends SuperEntity> implements Validator {
> Na minha opinião, existe uma carga intrínseca maior aí. Nesse caso eu preciso entender que preciso de uma Annotation na classe que chega no Controlador e a Classe que a implementa essa validação da anotação.
> Fora que não consigo reaproveitar a validação de unicidade de uma classe para outra usando o Spring Data JPA. Preciso da abstração do EntityManager e realizar a consulta usando CriteriaBuilder, CriteriaQuery, Root e Predicate. Na minha humilde opinião acho que está mais chatinho, já que temos mais abstrações kkkk.

A necessidade cognitiva de um código precisa ser avaliada sobre o ponto de vista de compensação. O validator da bean validation pode ter uma carga maior, acho que sim. A diferença é que você fez aquele código uma vez e utiliza uma annotation para sempre, em qualquer form. 

O validator que eu sugiro na Casa do código e o seu exigem que sejam feitas classes novas a cada validação. Na casa do código eu deveria ter criado uma validação da bean validation também, estava enviesado e fiquei no validator do Spring :).

2020-04-06 09:44 UTC, asouza approved these changes
Opa, estou aprovando pq acho que podemos seguir independente do seu approach em relação aos meus comentários. Só de você me perguntar e criticar de maneira construtiva minhas observações já mostra que você está tentando olhar o lado positivo e negativo das coisas. Se a pessoa sabe o que espera ganhar e o que pode perder, tudo está valendo :).

2020-04-07 01:01 UTC, albjoaov commented on src/main/java/com/mercadolibrewannabe/model/Category.java
> +public class Category extends SuperEntity {
Para finalizar essa questão, no PR #4 pude visualizar na prática que os pontos negativos foram maiores que os positivos. Acabei comentando lá. Valeuzão!

> Na verdade os padrões servem para tentar diminuir a carga intrínseca. Pense nos padrões, quando realmente bem adotados, como algo que te faz pensar menos :). Vou criar uma entidade, então já vou herdar de SuperEntity. A pessoa não necessariamente sabe o porque, mas vive bem e faz o que precisa ser feito.

Teoricamente foi o que tentei criar com essa SuperEntity, sacou? 
Talvez alguém possa ter essa linha de pensamento que eu tive ao criar a entidade base, veja se concorda:

> Vou criar uma entidade, então já vou herdar de SuperEntity

Exatamente por essa frase acima que acabei associando implicitamente na minha cabeça uma coisa (diminuição da carga intrínseca com a criação desse padrão) a outra (a `SuperEntity`). 

Além disso, como lidar com a linha tênue de criar um padrão e acabar gerando uma repetição de código desenfreada sem questionamento, como descrito na sua frase abaixo:

> A pessoa não necessariamente sabe o porque, mas vive bem e faz o que precisa ser feito.

2020-04-07 01:23 UTC, albjoaov commented on src/main/java/com/mercadolibrewannabe/model/validation/UniqueValidator.java
> +public abstract class UniqueValidator<F extends AbstractForm, E extends SuperEntity> implements Validator {
Entendi!

Contudo, ainda tenho algumas dúvidas em relação a esse Validator (`javax.validation.ConstraintValidator`):

1. No exemplo de Tarcisio ele está somente na camada de Validação do Controller. Ou seja, o Spring integrado a Bean Validation que está atuando nesse contexto. Nesse sentido, ele consegue injetar um EntityManager? A priori pensei que não iria funcionar. Até pelo seu vídeo no Canal do YT sobre isso.

2.  Se o `boolean isValid(T value, ConstraintValidatorContext context);` do `javax.validation.ConstraintValidator` retornar falso, o Spring continua lançando a exceção de `MethodArgumentNotValidException`? Pergunto pois quero saber se ainda vou conseguir definir mensagens customizadas/localizadas a partir disso.

2020-04-07 21:26 UTC, asouza approved these changes

2020-04-07 21:26 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/Category.java
> +	@CreatedDate
*A complicação do nosso é código é proporcional a complicação da nossa feature. Quanto mais simples, melhor.*

Aqui você pode iniciar com um código java padrão em vez de se apoiar numa feature do framework. Dessa forma, quando você instancia um objeto ele nasce sem data de criação.

2020-04-07 21:26 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/Category.java
> +	@LastModifiedDate
Aqui já é mais ok, já que a data de modificação não é um pedido de negócio. É mais um detalhe de auditoria que você quer testar.

2020-04-07 21:26 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/Category.java
> +	public void setId (UUID id) {
pq tem setters aqui?

2020-04-07 21:26 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/User.java
> +	public void setId (UUID id) {
mesma coisa para os setters aqui...

2020-04-07 23:33 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/Category.java
> +public class Category extends SuperEntity {
Opa, mal não ter respondido aqui. Eu saquei a intenção e acho que se no final, se você achar que vale a pena pensando numa escala mais larga, jogue duro. Olhando bem para pró e contra, vale tudo :).

2020-04-07 23:35 UTC, asouza commented on src/main/java/com/mercadolibrewannabe/model/validation/UniqueValidator.java
> +public abstract class UniqueValidator<F extends AbstractForm, E extends SuperEntity> implements Validator {
1. Ele só funciona no contexto do Spring mesmo. Para funcionar na entidade em si, teríamos que fazer alguma daquelas gambis que mostramos na live. Por outro lado, faz bastante sentido ela residir fora da entidade mesmo. 

2. Funciona lindamente :).

2020-04-08 05:20 UTC, merged